# Generated by Django 5.0.2 on 2024-03-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cloc', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('chiefjustice', models.CharField(max_length=255)),
                ('noj', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
