# Generated by Django 5.0.2 on 2024-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_court',
            name='image',
            field=models.ImageField(upload_to='court/'),
        ),
    ]
