# Generated by Django 5.0.2 on 2024-03-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_add_court_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_section', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('penalty', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('amendment_details', models.CharField(max_length=255)),
                ('provisions', models.CharField(max_length=255)),
                ('year_enacted', models.IntegerField()),
                ('applicability', models.CharField(max_length=255)),
            ],
        ),
    ]
