# Generated by Django 5.0.2 on 2024-03-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_profile',
            name='image',
            field=models.ImageField(default='', upload_to='image/'),
            preserve_default=False,
        ),
    ]
