# Generated by Django 3.2.4 on 2024-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0004_lawyer_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_profile',
            name='license_no',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
