# Generated by Django 5.0.2 on 2024-03-06 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_lawyer_profile_image'),
        ('user', '0002_contact_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_lawyer',
            name='lawyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lawyer.lawyer_profile'),
            preserve_default=False,
        ),
    ]
