# Generated by Django 5.0.2 on 2024-03-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
