# Generated by Django 5.0.2 on 2024-03-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_complete_profile_user_complete_profile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('password', models.TextField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='complete_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='complete_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='complete_profile',
            name='password',
        ),
        migrations.AddField(
            model_name='complete_profile',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.luser'),
            preserve_default=False,
        ),
    ]
