# Generated by Django 5.0.2 on 2024-03-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_luser_remove_complete_profile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luser',
            old_name='email',
            new_name='username',
        ),
    ]
