# Generated by Django 5.0.2 on 2024-03-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_email_luser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luser',
            name='username',
            field=models.EmailField(max_length=20),
        ),
    ]
