# Generated by Django 5.0.2 on 2024-04-03 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0003_reply'),
        ('user', '0011_delete_luser_remove_contact_lawyer_lawyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_lawyer',
            name='lawyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lawyer.lawyer_profile'),
            preserve_default=False,
        ),
    ]
